EPSILON = 1e-5
CURVE_RESOLUTION = 16
REMESH = True
REMESH_RESOLUTION = 9

COMPLIANCE_LENGTH = 3
COMPLIANCE_THICKNESS = 1.1
COMPLIANCE_FILLET_RADIUS = COMPLIANCE_LENGTH / 2

X_SIZE, Y_SIZE, THICKNESS = 6, 15, 2
X_GRID, Y_GRID = 5, 4

ASYMMETRIC_RATIO = 2.5

SUPPORT_WIDTH, SUPPORT_HEIGHT = COMPLIANCE_THICKNESS * 2, COMPLIANCE_LENGTH
FLANGE_HEIGHT, FLANGE_THICKNESS = 7, THICKNESS

TILE_BOTTOM, TILE_CENTER, TILE_TOP = True, False, False
# TILE_BOTTOM, TILE_CENTER, TILE_TOP = False, False, True
